### ISSUE TITLE
Unable to use the tool in VS 2019

### ISSUE THREAD

**Issue by Grendizr** [spadapet/xaml-binding-tool#29]
Hi,

This is what I get during my debug session :

```
An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\_\AppData\Roaming\Microsoft\VisualStudio\16.0_2c572b5e\ActivityLog.xml".

Exception details:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControl' to type 'Microsoft.VisualStudio.Shell.TableControl.IWpfTableControl4'.
   at XamlBinding.ToolWindow.BindingPaneControl..ctor(IServiceProvider serviceProvider, BindingPaneViewModel viewModel)
   at XamlBinding.ToolWindow.BindingPane..ctor(BindingPackage package)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.VisualStudio.Shell.Package.InstantiateToolWindow(Type toolWindowType, Object context)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<CompleteToolWindowCreationAsync>d__35.MoveNext()
```

Any advice ?

Thanks

**Comment by spadapet** [comment]
@Grendizr It looks like the interface IWpfTableControl4 isn't always supported in VS 2019. I'll probably just scale back and use a previous version of that interface that is guaranteed to be available.

What update of VS 2019 are you using?

**Comment by spadapet** [comment]
I made a fix to just use IWpfTableControl instead of IWpfTableControl4, didn't even need the newer version. Version 1.26 of the extension will be available shortly and will contain the fix.

Commit 6e9c4c7bf34e02f2b43909e6ef6ff602ce34d2e2
